<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [2]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [75]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((3, 3))
b = np.random.sample((3, 3))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
print(np.ndim(a))
print(np.ndim(b))
# ========
print(a)
print(b)

2
2
[[0.97601142 0.10118734 0.77650194]
 [0.4915006  0.10757469 0.94427876]
 [0.86254264 0.1159482  0.80875656]]
[[7.08578017e-01 8.20702153e-03 5.91544078e-01]
 [2.81572571e-01 5.03114152e-01 1.64333835e-04]
 [8.64200610e-01 1.78266263e-01 1.17689317e-01]]


In [40]:
def no_numpy_mult(first, second):
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy
    """

    dim = len(first) # узнаем количество строк в матрице, тк она квадратная то это и кол-во столбцов

    #просто
    # output_matrix = [[0,0,0] for i in range(dim)] # делаем шаблон выходной матрицы

    # for i in range(dim):
    #     for j in range(dim):
    #         output_matrix[i][j] = sum([first[i][k] * second[k][j] for k in range(dim)])
    # result = output_matrix

    #list comprehension
    result = [[sum([first[i][k] * second[k][j] for k in range(dim)]) for j in range(dim)] for i in range(dim)]

    return result

In [32]:
matr_1 = [[1,1,1],[1,1,1],[1,1,1]]
matr_2 = [[2,2,2],[2,2,2],[2,2,2]]

In [64]:
no_numpy_mult(matr_1,matr_2)

[[6, 6, 6], [6, 6, 6], [6, 6, 6]]

In [59]:
def numpy_mult(first, second):
    """  
    a: np.array[size, size]             --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    #YOUR CODE: please use numpy
    # result = #YOUR CODE: create np.array


    # result = first @ second
    result = first.dot(second)
    return result

In [60]:
matr_np_1 = np.array([[1,1,1],[1,1,1],[1,1,1]])
matr_np_2 = np.array([[2,2,2],[2,2,2],[2,2,2]])

In [61]:
numpy_mult(matr_np_1,matr_np_2)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [69]:
%%time
# засечем время работы функции без NumPy
M1 = no_numpy_mult(a, b)

CPU times: user 66 µs, sys: 1e+03 ns, total: 67 µs
Wall time: 68.9 µs


In [70]:
%%time
# засечем время работы функции с NumPy
M2 = numpy_mult(a, b)

CPU times: user 229 µs, sys: 155 µs, total: 384 µs
Wall time: 351 µs


In [71]:
M1

[[0.766931305614613, 0.910220338074041, 0.7991349752071639],
 [0.4500152806552028, 0.5425164689296267, 0.48714370442596705],
 [0.3992196634155344, 0.4892976461737456, 0.15719422141938286]]

In [73]:
M2

array([[0.76693131, 0.91022034, 0.79913498],
       [0.45001528, 0.54251647, 0.4871437 ],
       [0.39921966, 0.48929765, 0.15719422]])

In [72]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [3]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.02274008 0.64306036 0.47584789] [0.28406416 0.97699836 0.57665366]


In [9]:
def no_numpy_scalar(v1, v2):
    """  
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """
    v_length = len(v1)
    result = sum([v1[i] * v2[i] for i in range(v_length)])
    return result

In [ ]:
c1 = [1,1,1]

In [ ]:
c2 = [2,2,2]

In [16]:
no_numpy_scalar(c1,c2)

6

In [17]:
def numpy_scalar (v1, v2):
    """  
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """

    result = v1@v2
    return result

In [20]:
d1 = np.array([1,1,1])
d2 = np.array([2,2,2])

In [21]:
numpy_scalar(d1,d2)

6

In [24]:
product_1 = no_numpy_scalar(a,b)
product_2 = numpy_scalar(a,b)

In [25]:
%time product_1

CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 6.2 µs


0.9091279777259783

In [27]:
%time product_2

CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 3.81 µs


0.9091279777259783

In [28]:
# проверим корректность:
assert np.allclose(product_1, product_2)

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [43]:
def diag_2k(a):
    """  
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    diagonal = np.diag(a)
    even_diag_numb = diagonal[diagonal % 2 == 0]
    result = sum(even_diag_numb)
    return result

In [44]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[2, 6, 6, 1, 8],
       [4, 1, 1, 9, 7],
       [6, 9, 2, 6, 7],
       [9, 2, 7, 5, 9],
       [8, 6, 4, 3, 5]])

In [45]:
%%time
# засечем время работы функции с NumPy
diag_2k(a)

CPU times: user 82 µs, sys: 5 µs, total: 87 µs
Wall time: 102 µs


4

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​ 

In [12]:
def cumsum(A):
    """  
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """

    result = np.cumsum(A,axis=1)
    return result

In [13]:
# зададим некоторую последовательность и проверим ее на вашей функции. 
A = sps.uniform.rvs(size=10**3) 

%time S2 = cumsum(A)

AxisError: axis 1 is out of bounds for array of dimension 1

In [10]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [11]:
np.cumsum(a,axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

In [14]:
cumsum(a)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [151]:
from copy import copy
def np_transformation(X, a=1):
    """  
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются 
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и 
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке, 
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    matr_copy=X.copy()
    matr_copy_pow3=matr_copy**3
    matr_copy_pow3[::,1::2]=a
    result = np.hstack((matr_copy,matr_copy_pow3[::,::-1]))
    return result


In [136]:
X = np.array([[i for i in range(1, 10, 2)]])
%time S2 = np_transformation(X, 5)

CPU times: user 143 µs, sys: 247 µs, total: 390 µs
Wall time: 313 µs


In [140]:
tm1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [152]:
np_transformation(tm1, 5)

array([[  1,   2,   3,   4,   5, 125,   5,  27,   5,   1],
       [  1,   2,   3,   4,   5, 125,   5,  27,   5,   1]])

### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [388]:
def np_encode(a):
    """  
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора 
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые 
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор 
    repetitions добавляет длины последовательностей подряд идущих повторений. 
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    Anew=np.array(list(a[-1:])+list(a[:-1])) # создаем новый массив семещенный на один элемент
    elts = a[Anew != a] #по маске выводим элементы те что тру то есть не равны поэлементно - значит найдем первые элементы в массиве
    nonzero = np.nonzero(Anew != a)[0] # найдем индексы первых элементов
    repeats = np.diff(np.append(nonzero,a.size)) # разница между i+1 - i индексами покажет сколько повторяющихся цифр между этими индексами, то есть между индексом каждой новой цифроф новой группы повторяющихся цифр

    return (elts,repeats)

In [374]:
def np1_encode(a):
    elts = np.array([],dtype='int16')
    reps = np.array([],dtype='int16')
    for key, group in itertools.groupby(a):

        li = list(group)
        elts = np.append(elts,key)
        reps = np.append(reps,len(li))

        # print('key {} has len {}: {}'.format(key, len(li), li))
    return (elts,reps)

In [350]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

CPU times: user 76 µs, sys: 19 µs, total: 95 µs
Wall time: 89.9 µs


In [340]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

In [389]:
np_encode(X)

(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))

In [300]:
import itertools

In [372]:
elts = np.array([],dtype='int16')
reps = np.array([],dtype='int16')
for key, group in itertools.groupby(X):

    li = list(group)
    elts = np.append(elts,key)
    reps = np.append(reps,len(li))

    print('key {} has len {}: {}'.format(key, len(li), li))
print(elts,reps)

key 1 has len 1: [1]
key 2 has len 2: [2, 2]
key 3 has len 2: [3, 3]
key 1 has len 2: [1, 1]
key 5 has len 2: [5, 5]
key 2 has len 1: [2]
key 3 has len 2: [3, 3]
[1 2 3 1 5 2 3] [1 2 2 2 2 1 2]


In [371]:
type(elts)

numpy.ndarray

In [352]:
[(x, list(y)) for x, y in itertools.groupby(X)]

[(1, [1]),
 (2, [2, 2]),
 (3, [3, 3]),
 (1, [1, 1]),
 (5, [5, 5]),
 (2, [2]),
 (3, [3, 3])]

In [376]:
X[1:] != X[:-1]

array([ True, False,  True, False,  True, False,  True, False,  True,
        True, False])

In [378]:
X[:-1]

array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3])

In [302]:
X

array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

In [306]:
X[-1:]

array([3])

In [307]:
X[:-1]

array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3])

In [359]:
Xnew=np.array(list(X[-1:])+list(X[:-1]))
Xnew

array([3, 1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3])

In [360]:
X

array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

In [361]:
Xnew != X

array([ True,  True, False,  True, False,  True, False,  True, False,
        True,  True, False])

In [362]:
elts = X[Xnew != X]
elts

array([1, 2, 3, 1, 5, 2, 3])

In [386]:
nonzero = np.nonzero(Xnew != X)[0]
nonzero

array([ 0,  1,  3,  5,  7,  9, 10])

In [391]:
X

array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

In [390]:
np.append(nonzero,X.size)

array([ 0,  1,  3,  5,  7,  9, 10, 12])

In [387]:
np.diff(np.append(nonzero,X.size))

array([1, 2, 2, 2, 2, 1, 2])

In [380]:
np.diff(X) != 0

array([ True, False,  True, False,  True, False,  True, False,  True,
        True, False])

In [381]:
np.insert(np.diff(X) != 0,[0],[True])

array([ True,  True, False,  True, False,  True, False,  True, False,
        True,  True, False])

In [384]:
np.nonzero(np.insert(np.diff(X) != 0,[0],[True]))[0]

array([ 0,  1,  3,  5,  7,  9, 10])